## Project
name: tasty_bytes
version: "1.0"
config-version: 2
profile: tasty_bytes

## Sources
model-paths: [models]
analysis-paths: [analysis]
test-paths: [tests]
seed-paths: [seeds]
macro-paths: [macros]
snapshot-paths: [snapshots]

## Hooks (ここに追加)
on-run-end:
  - "{{ on_run_end(results) }}"

## Target
target-path: target
clean-targets: [target, dbt_modules]

models:
  staging:
    +tags: ['staging']
  marts:
    +tags: ['model']
