{{ config(
    materialized='incremental',
    database='TASTY_BYTES_DBT_DB',
    schema='silver_cleansing',
    alias='T_JYUTYU',
    unique_key=['JYUTYU_KEY', 'ANKEN_NO']
) }}

SELECT
    -- 1 - 10
    TO_NUMBER(JYUTYU_KEY)              AS JYUTYU_KEY,
    TO_NUMBER(ANKEN_NO)                AS ANKEN_NO,
    MITSUMORI_NO,
    TO_NUMBER(KEIYAKU_KEY)             AS KEIYAKU_KEY,
    JYUTYU_NO,
    KEIRI_JYUTYU_NO,
    SYU_KOUJI_NO,
    TO_NUMBER(KOUJI_KEY)               AS KOUJI_KEY,
    SEIHIN_BUNRUI_CD,
    KEIYAKUU_NAIYOU_KBN_CD,

    -- 11 - 20
    SENKOU_BUNRUI_CD,
    SEIHIN_KBN_CD,
    KOUJI_NAME,
    KOUJI_NAME_KANA,
    KOUJI_RYAKU_NAME,
    ONSEN_KENRIKIN_KBN,
    TO_NUMBER(MITSUMORI_GENKA)         AS MITSUMORI_GENKA,
    TO_NUMBER(TOKUBETSU_HANSOKUHI)     AS TOKUBETSU_HANSOKUHI,
    TO_NUMBER(SERVICE_KOUJI_GENKA)     AS SERVICE_KOUJI_GENKA,
    TO_NUMBER(MITSUMORI_KINGAKU)       AS MITSUMORI_KINGAKU,

    -- 21 - 30
    TO_NUMBER(NEBIKI_GAKU)              AS NEBIKI_GAKU,
    TO_NUMBER(JYUTYU_KINGAKU)           AS JYUTYU_KINGAKU,
    TO_NUMBER(SYOUHI_ZEI)               AS SYOUHI_ZEI,
    TO_NUMBER(JYUTYU_KINGAKU_ZEIKOMI)  AS JYUTYU_KINGAKU_ZEIKOMI,
    KAZEI_KBN_CD,
    ZEIRITSU_KBN_CD,
    JYUTYU_KEIJOU_TAISYOU_KBN,
    TO_TIMESTAMP_NTZ(JYUTYU_KEIJYOU_DATE)  AS JYUTYU_KEIJYOU_DATE,
    TO_TIMESTAMP_NTZ(ITAKU_KEIJYOU_DATE)   AS ITAKU_KEIJYOU_DATE,
    TO_TIMESTAMP_NTZ(JYUTAKU_KEIJYOU_DATE) AS JYUTAKU_KEIJYOU_DATE,

    -- 31 - 40
    TO_TIMESTAMP_NTZ(URIAGE_KEIJYOU_DATE)        AS URIAGE_KEIJYOU_DATE,
    TO_TIMESTAMP_NTZ(JYUTYU_TORIKESHI_DATE)      AS JYUTYU_TORIKESHI_DATE,
    TO_TIMESTAMP_NTZ(ITAKU_TORIKESHI_DATE)       AS ITAKU_TORIKESHI_DATE,
    TO_TIMESTAMP_NTZ(JYUTAKU_TORIKESHI_DATE)     AS JYUTAKU_TORIKESHI_DATE,
    TO_TIMESTAMP_NTZ(URIAGE_TORIKESHI_DATE)      AS URIAGE_TORIKESHI_DATE,
    SAKUJYO_KBN,
    TOUROKU_USER_ID,
    KOUSHIN_USER_ID,
    SAKUJYO_USER_ID,
    TO_TIMESTAMP_NTZ(TOUROKU_DATE)               AS TOUROKU_DATE,

    -- 41 - 50
    TO_TIMESTAMP_NTZ(KOUSHIN_DATE)                AS KOUSHIN_DATE,
    TO_TIMESTAMP_NTZ(SAKUJYO_DATE)                AS SAKUJYO_DATE,
    TO_NUMBER(EIGYOUKEN_HUTANKIN)                  AS EIGYOUKEN_HUTANKIN,
    TO_NUMBER(AFTER_BUNTAN)                        AS AFTER_BUNTAN,
    NEBIKI_RIYU_CD,
    NEBIKI_RIYU_MEMO,
    TO_TIMESTAMP_NTZ(JYUTYU_KEIJYOU_IRAI_DATE)     AS JYUTYU_KEIJYOU_IRAI_DATE,
    TO_TIMESTAMP_NTZ(JYUTYU_TORIYAME_IRAI_DATE)    AS JYUTYU_TORIYAME_IRAI_DATE,
    TO_TIMESTAMP_NTZ(JYUTYU_KEIJYOU_KANRYOU_DATE)  AS JYUTYU_KEIJYOU_KANRYOU_DATE,
    TO_TIMESTAMP_NTZ(ITAKU_KEIJYOU_IRAI_DATE)      AS ITAKU_KEIJYOU_IRAI_DATE,

    -- 51 - 61
    TO_TIMESTAMP_NTZ(ITAKU_TORIYAME_IRAI_DATE)     AS ITAKU_TORIYAME_IRAI_DATE,
    TO_TIMESTAMP_NTZ(ITAKU_KEIJYOU_KANRYOU_DATE)   AS ITAKU_KEIJYOU_KANRYOU_DATE,
    TO_TIMESTAMP_NTZ(URIAGE_KEIJYOU_IRAI_DATE)     AS URIAGE_KEIJYOU_IRAI_DATE,
    SAIKEIJOU_KBN,
    ITAKU_TORIKESHI_KBN,
    TO_NUMBER(MINASHI_JYUTYU_KIN)                  AS MINASHI_JYUTYU_KIN,
    TO_NUMBER(MITSUMORI_KINGAKU_100)               AS MITSUMORI_KINGAKU_100,
    TO_NUMBER(NEBIKI_GAKU_100)                     AS NEBIKI_GAKU_100,
    TO_NUMBER(JYUTYU_KINGAKU_100)                  AS JYUTYU_KINGAKU_100,
    TO_NUMBER(SYOUHI_ZEI_100)                      AS SYOUHI_ZEI_100,
    TO_NUMBER(JYUTYU_KINGAKU_ZEIKOMI_100)          AS JYUTYU_KINGAKU_ZEIKOMI_100,

    -- 管理列
    INGEST_TIMESTAMP,
    CURRENT_TIMESTAMP() AS UPDATE_TIMESTAMP

FROM {{ ref('raw_ref') }}
{% if is_incremental() %}
WHERE INGEST_TIMESTAMP >
      (SELECT COALESCE(MAX(INGEST_TIMESTAMP), '1970-01-01'::TIMESTAMP_NTZ)
       FROM {{ this }})
{% endif %}
QUALIFY ROW_NUMBER() OVER (
  PARTITION BY JYUTYU_KEY, ANKEN_NO
  ORDER BY INGEST_TIMESTAMP DESC
) = 1
