{{ config(
    materialized='incremental',
    database='SILVER',
    schema='CLN',
    alias='T_JYUTYU',
    unique_key=['JYUTYU_KEY', 'ANKEN_NO'],
    tags=['silver']
) }}

SELECT
    -- 数値項目はTRIM不要、文字列項目（MITSUMORI_NOなど）にTRIMを適用
    -- 1 - 10
    TO_NUMBER(JYUTYU_KEY)              AS JYUTYU_KEY,
    TO_NUMBER(ANKEN_NO)                AS ANKEN_NO,
    TRIM(MITSUMORI_NO)                 AS MITSUMORI_NO,
    TO_NUMBER(KEIYAKU_KEY)             AS KEIYAKU_KEY,
    TRIM(JYUTYU_NO)                    AS JYUTYU_NO,
    TRIM(KEIRI_JYUTYU_NO)              AS KEIRI_JYUTYU_NO,
    TRIM(SYU_KOUJI_NO)                 AS SYU_KOUJI_NO,
    TO_NUMBER(KOUJI_KEY)               AS KOUJI_KEY,
    TRIM(SEIHIN_BUNRUI_CD)             AS SEIHIN_BUNRUI_CD,
    TRIM(KEIYAKU_NAIYOU_KBN_CD)        AS KEIYAKU_NAIYOU_KBN_CD, 

    -- 11 - 20
    TRIM(SENKOU_BUNRUI_CD)             AS SENKOU_BUNRUI_CD,
    TRIM(SEIHIN_KBN_CD)                AS SEIHIN_KBN_CD,
    TRIM(KOUJI_NAME)                   AS KOUJI_NAME,
    TRIM(KOUJI_NAME_KANA)              AS KOUJI_NAME_KANA,
    TRIM(KOUJI_RYAKU_NAME)             AS KOUJI_RYAKU_NAME,
    TRIM(ONSEN_KENRIKIN_KBN)           AS ONSEN_KENRIKIN_KBN,
    TO_NUMBER(MITSUMORI_GENKA)         AS MITSUMORI_GENKA,
    TO_NUMBER(TOKUBETSU_HANSOKUHI)     AS TOKUBETSU_HANSOKUHI,
    TO_NUMBER(SERVICE_KOUJI_GENKA)     AS SERVICE_KOUJI_GENKA,
    TO_NUMBER(MITSUMORI_KINGAKU)       AS MITSUMORI_KINGAKU,

    -- 21 - 30
    TO_NUMBER(NEBIKI_GAKU)              AS NEBIKI_GAKU,
    TO_NUMBER(JYUTYU_KINGAKU)           AS JYUTYU_KINGAKU,
    TO_NUMBER(SYOUHI_ZEI)               AS SYOUHI_ZEI,
    TO_NUMBER(JYUTYU_KINGAKU_ZEIKOMI)   AS JYUTYU_KINGAKU_ZEIKOMI,
    TRIM(KAZEI_KBN_CD)                  AS KAZEI_KBN_CD,
    TRIM(ZEIRITSU_KBN_CD)               AS ZEIRITSU_KBN_CD,
    TRIM(JYUTYU_KEIJOU_TAISYOU_KBN)     AS JYUTYU_KEIJOU_TAISYOU_KBN,
    TO_TIMESTAMP_NTZ(JYUTYU_KEIJYOU_DATE)  AS JYUTYU_KEIJYOU_DATE,
    TO_TIMESTAMP_NTZ(ITAKU_KEIJYOU_DATE)   AS ITAKU_KEIJYOU_DATE,
    TO_TIMESTAMP_NTZ(JYUTAKU_KEIJYOU_DATE) AS JYUTAKU_KEIJYOU_DATE,

    -- 31 - 40
    TO_TIMESTAMP_NTZ(URIAGE_KEIJYOU_DATE)        AS URIAGE_KEIJYOU_DATE,
    TO_TIMESTAMP_NTZ(JYUTYU_TORIKESHI_DATE)      AS JYUTYU_TORIKESHI_DATE,
    TO_TIMESTAMP_NTZ(ITAKU_TORIKESHI_DATE)       AS ITAKU_TORIKESHI_DATE,
    TO_TIMESTAMP_NTZ(JYUTAKU_TORIKESHI_DATE)     AS JYUTAKU_TORIKESHI_DATE,
    TO_TIMESTAMP_NTZ(URIAGE_TORIKESHI_DATE)      AS URIAGE_TORIKESHI_DATE,
    TRIM(SAKUJYO_KBN)                            AS SAKUJYO_KBN,
    TRIM(TOUROKU_USER_ID)                        AS TOUROKU_USER_ID,
    TRIM(KOUSHIN_USER_ID)                        AS KOUSHIN_USER_ID,
    TRIM(SAKUJYO_USER_ID)                        AS SAKUJYO_USER_ID,
    TO_TIMESTAMP_NTZ(TOUROKU_DATE)               AS TOUROKU_DATE,

    -- 41 - 50
    TO_TIMESTAMP_NTZ(KOUSHIN_DATE)                AS KOUSHIN_DATE,
    TO_TIMESTAMP_NTZ(SAKUJYO_DATE)                AS SAKUJYO_DATE,
    TO_NUMBER(EIGYOUKEN_HUTANKIN)                 AS EIGYOUKEN_HUTANKIN,
    TO_NUMBER(AFTER_BUNTAN)                       AS AFTER_BUNTAN,
    TRIM(NEBIKI_RIYU_CD)                          AS NEBIKI_RIYU_CD,
    TRIM(NEBIKI_RIYU_MEMO)                        AS NEBIKI_RIYU_MEMO,
    TO_TIMESTAMP_NTZ(JYUTYU_KEIJYOU_IRAI_DATE)    AS JYUTYU_KEIJYOU_IRAI_DATE,
    TO_TIMESTAMP_NTZ(JYUTYU_TORIYAME_IRAI_DATE)   AS JYUTYU_TORIYAME_IRAI_DATE,
    TO_TIMESTAMP_NTZ(JYUTYU_KEIJYOU_KANRYOU_DATE) AS JYUTYU_KEIJYOU_KANRYOU_DATE,
    TO_TIMESTAMP_NTZ(ITAKU_KEIJYOU_IRAI_DATE)     AS ITAKU_KEIJYOU_IRAI_DATE,

    -- 51 - 61
    TO_TIMESTAMP_NTZ(ITAKU_TORIYAME_IRAI_DATE)     AS ITAKU_TORIYAME_IRAI_DATE,
    TO_TIMESTAMP_NTZ(ITAKU_KEIJYOU_KANRYOU_DATE)   AS ITAKU_KEIJYOU_KANRYOU_DATE,
    TO_TIMESTAMP_NTZ(URIAGE_KEIJYOU_IRAI_DATE)     AS URIAGE_KEIJYOU_IRAI_DATE,
    TRIM(SAIKEIJOU_KBN)                            AS SAIKEIJOU_KBN,
    TRIM(ITAKU_TORIKESHI_KBN)                      AS ITAKU_TORIKESHI_KBN,
    TO_NUMBER(MINASHI_JYUTYU_KIN)                  AS MINASHI_JYUTYU_KIN,
    TO_NUMBER(MITSUMORI_KINGAKU_100)               AS MITSUMORI_KINGAKU_100,
    TO_NUMBER(NEBIKI_GAKU_100)                     AS NEBIKI_GAKU_100,
    TO_NUMBER(JYUTYU_KINGAKU_100)                  AS JYUTYU_KINGAKU_100,
    TO_NUMBER(SYOUHI_ZEI_100)                      AS SYOUHI_ZEI_100,
    TO_NUMBER(JYUTYU_KINGAKU_ZEIKOMI_100)          AS JYUTYU_KINGAKU_ZEIKOMI_100,
    
    -- メタデータ・管理列
    TRIM(METADATA_SYSTEMNAME)                      AS METADATA_SYSTEMNAME,
    TRIM(METADATA_FILENAME)                        AS METADATA_FILENAME,
    METADATA_FILE_ROW_NUMBER,
    TRIM(METADATA_FILE_CONTENT_KEY)                AS METADATA_FILE_CONTENT_KEY,
    METADATA_FILE_LAST_MODIFIED,
    METADATA_START_SCAN_TIME,
    INGEST_TIMESTAMP,
    CURRENT_TIMESTAMP()                            AS UPDATE_TIMESTAMP

FROM {{ ref('raw_ref') }}

{% if is_incremental() %}
WHERE REGEXP_SUBSTR(METADATA_FILENAME, '\\d{17,}')
      >
      (
        SELECT COALESCE(
          MAX(REGEXP_SUBSTR(METADATA_FILENAME, '\\d{17,}')), '19700101000000000'
        )
        FROM {{ this }}
      )
{% endif %}

QUALIFY ROW_NUMBER() OVER (
  PARTITION BY JYUTYU_KEY, ANKEN_NO
  ORDER BY REGEXP_SUBSTR(METADATA_FILENAME, '\\d{17,}') DESC
) = 1
